---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: doaadmin-deployment
  namespace: doaadmin
spec:
  selector:
    matchLabels:
      app: doaadmin
  replicas: 1
  template:
    metadata:
      labels:
        app: doaadmin
    spec:
      containers:
      - name: pods-doaadmin-deployment
        image: localhost:32000/doaadmin:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "1Gi"
            cpu: "1000m"
          limits:
            memory: "1.8Gi"
            cpu: "1800m"
        volumeMounts:
         - name: doaadmin-production-data
           mountPath: "/www/public/data"
        env:
        - name: PROVISIONER_NAME
          value: ksemin.in/nfs
        - name: NFS_SERVER
          value: 92.204.134.92
        - name: NFS_PATH
          value: /
      volumes:
      - name: doaadmin-production-data
        nfs:
          server: 92.204.134.92
          path: /data/apps/doaadmin
---
apiVersion: v1
kind: Service
metadata:
    name: doaadmin-service
    namespace: doaadmin
spec:
  selector:
    app: doaadmin
  type: ClusterIP
  ports:
    - protocol: TCP
      name: https
      port: 80
      targetPort: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: doaadmin-in-ingress
 namespace: doaadmin
 annotations:
   cert-manager.io/cluster-issuer: letsencrypt
spec:
 ingressClassName: public
 tls:
 - hosts:
   - doaadmin.bynaricexam.com
   secretName: doaadmin-in-ingress-tls
 rules:
 - host: doaadmin.bynaricexam.com
   http:
     paths:
     - backend:
         service:
           name: doaadmin-service
           port:
             number: 80
       path: /
       pathType: Prefix
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: doaadmin-hpa
  namespace: doaadmin
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: doaadmin-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
